### ISSUE TITLE
[HELP] - Auto Index not working

### ISSUE THREAD

**Issue by overcast404** [Aerilym/photoprism-helper#6]
I think I set it correct, but the photoprism's content changed nothing. 
I cant't find any error info in the log.
----------------------------------------------------------------------
It's log:
[2022-09-01 16:29:52] info: Timezone set to Asia/Shanqhai
[2022-09-01 16:29:52] warn: Env var ISDOCKER is set to true. If the application is not running in a docker container, change this to false.
[2022-09-01 16:29:52] info: Targeting PhotoPrism instance at http://10.1.1.99:2342/
[2022-09-01 16:29:52] info: PhotoPrism Helper API listening on port 2343
[2022-09-03 03:50:02] info: Timezone set to Asia/Shanqhai
[2022-09-03 03:50:02] warn: Env var ISDOCKER is set to true. If the application is not running in a docker container, change this to false.
 
only index true:
cron: 0 0 3,12,19 * * ? 
----------------------------------------

**Comment by Aerilym** [comment]
I will investigate this further but I have noticed some issues that might be causing the cron to not work, so give them a try first:
> [2022-09-01 16:29:52] info: Timezone set to Asia/Shanqhai

The timezone looks to be improperly set, it seems you wrote "Shanqhai" rather than "Shanghai" See the list of valid timezones: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

The log should also be reporting "Scheduling auto import task." or  "Scheduling auto index task." if either task has been successfully enabled and scheduled. Make sure you understand the difference between import and index. https://docs.photoprism.app/user-guide/library/

1. Please ensure you have the latest version installed as I make some fixes over the past week. 
2. Please ensure you have set the correct environment variables. It seems like you are trying to enable auto index so the following be set:
AUTO_INDEX = true
AUTO_INDEX_CRON =  0 0 3,12,19 * * ?

The AUTO_INDEX_CRON value will be validated and if it is invalid you will get a message in the log.

IMPORTANT: If you don't get the log message "Scheduling auto index task." then it is not enabled or failed to schedule.
You will also get a log message every time it triggers.

I will investigate this further later on but for now try what I have suggested and please let me know if it fixes or if you have any questions.

**Comment by Aerilym** [comment]
In the latest release, I have added a timezone checker to ensure added timezones are correct and can be used. Let me know if you fix the issue or need any more help.
